title: Awesome AMP
description: 👓 A curated list of AMP (Accelerated Mobile Pages) repos, examples, starters, tutorials, components, modules, videos, and anything else useful.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
include:
  - README.md
